pipeline {
    agent none

    environment {
        mvnHome = tool 'maven-3.9.4'
        dockerHome = tool 'MyDocker'
        dockerImageTag = "spring-img${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                script {
                    git 'https://github.com/foufa102022/backind-spingboot.git'
                }
            }
        }

        stage('Build Project') {
            steps {
                script {
                    sh "'${mvnHome}/bin/mvn' -B -DskipTests clean package"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker -H tcp://192.168.43.130:2375 build -t ${dockerImageTag} Backend/crowdapp"
                }
            }
        }

        stage('Deploy Docker Image') {
            steps {
                script {
                    echo "Docker Container spring boot container deleting..."
                    sh "docker -H tcp://192.168.43.130:2375 rm -f spring-cont"
                    echo "Docker Image Tag Name: ${dockerImageTag}"
                    sh "docker -H tcp://192.168.43.130:2375 run --name spring-cont -d -p 2222:8080 ${dockerImageTag}"
                }
            }
        }
    }
}
