pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Récupérez les sources du référentiel Git
                    checkout scm
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Changez de répertoire vers le dossier de votre application
                    dir('Backend/crowdapp') {
                        // Exécutez la commande Maven pour nettoyer et construire le projet
                        bat './mvnw clean install'
                    }
                }
            }
        }
 }
}




// pipeline {
//    agent any
//     stages {
          
//        stage('Build and Package') {
//             steps {
//                 script {
//                     // node {
//                     //     def mvnHome = tool 'maven-3.9.5'
//                     //     def dockerImage = 'spring-img'
//                     //     def dockerImageTag = "chetouiiftikhar/spring-img:${BUILD_ID}"

//                         sh 'Backend/crowdapp && ./mvnw -DskipTests clean install --fail-at-end'
//                     }
//                 //}
//             }
//         }
//         stage('Build Docker Image') {
//             steps {
//                 script {
//                     sh 'cd .. && docker rm -f back_container && docker build -t spring-img_%BUILD_ID% .'
//                 }
//             }
//         }
//         // stage('Tag and Push Docker Image') {
//         //     steps {
//         //         script {
//         //             sh "docker tag ${dockerImage}:latest ${dockerImageTag}"
//         //             sh "docker login -u *** -p *****"
//         //             sh "docker push ${dockerImageTag"
//         //         }
//         //     }
//         // }
//         stage('Run Docker Container') {
//             steps {
//                 script {
//                     sh 'docker run -p 8888:8080 -dit --name back_container spring-img_%BUILD_ID%'
//                 }
//             }
//         }
//    }
// }

