pipeline {
    agent any

    stages {
        stage('Build and Package') {
            steps {
                dir('Backend/crowdapp') {
                    script {
                        // Exécuter la commande Maven pour construire le projet Spring Boot
                        sh 'mvnw -DskipTests clean install --fail-at-end'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Exécuter la commande pour construire l'image Docker
                    sh 'docker rm -f back_container && true' // Supprimer le conteneur Docker s'il existe
                    sh 'docker build -t spring-img .'
                }
            }
        }

        stage('Deploy Docker Image') {
            steps {
                script {
                    // Exécuter la commande pour exécuter un conteneur Docker
                    sh 'docker run -p 8888:8080 -dit --name back_container chetouiiftikhar/spring-img:$BUILD_ID'
                }
            }
        }
    }
}
